package kabox.fitmate;

import kabox.fitmate.Model.User;
import kabox.fitmate.Repository.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;
import kabox.fitmate.Model.Role;
import java.util.Optional;

@Configuration
public class DataInitializer {


    @Bean
    public CommandLineRunner initDatabase(UserRepository userRepository, PasswordEncoder passwordEncoder) {

        return args -> {


            Optional<User> existingAdmin = userRepository.findByEmail("admin@fitmate.com");

            if (existingAdmin.isEmpty()) {

                // Password "admin123" encoded with BCrypt
                // Hash is only used for test purposes and should be generated by PasswordEncoder

                User adminUser = new User();
                adminUser.setUsername("admin");
                adminUser.setEmail("admin@fitmate.com");
                adminUser.setPassword(passwordEncoder.encode("admin123"));


                adminUser.setRole(Role.ADMIN);


                adminUser.setAvatarUrl("");

                userRepository.save(adminUser);

                System.out.println("Utworzono użytkownika administracyjnego: 'admin' (admin123)");
            }

        };
    }
}
